name: Minishell tester (Norme & Minishell tester)

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

      # Installation de libreadline-dev
    - name: Install dependencies
      run: sudo apt-get install -y libreadline-dev

    # Installation de norminette
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install norminette
      run: |
        python -m pip install --upgrade pip
        pip install norminette

    # Vérification de la norme
    - name: Check norm
      run: |
        norminette

    # Compilation du projet
    - name: Build project
      run: |
        make
        make clean

    # Clonage du tester
    - name: Clone tester
      run: |
        git clone https://github.com/LucasKuhn/minishell_tester.git

    # Exécution du tester
    - name: Run tester
      run: |
        make
        cd minishell_tester
        ./tester
